# Generated by Django 3.1 on 2022-06-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=100, verbose_name='User Name')),
                ('user_image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
